openapi: 3.1.0
info:
  title: SoundPad Flex API
  version: 1.0.0

servers:
  - url: https://dc013b7cc843.ngrok-free.app

paths:
  /ping:
    get:
      summary: Health-check
      operationId: ping
      responses:
        '200':
          description: Pong
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: pong
