openapi: 3.0.1
info:
  title: SoundPad Flex API
  version: 1.0.0
  description: A simple soundboard API for playing custom sound clips

servers:
  - url: https://soundpad-flex.ngrok.io

paths:
  /sounds:
    get:
      summary: List sounds
      operationId: listSounds
      responses:
        "200":
          description: Array of sounds
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sound"

    post:
      summary: Upload sound
      operationId: uploadSound
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Sound uploaded successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sound"

  /sounds/{id}/play:
    get:
      summary: Play sound
      operationId: playSound
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Sound played successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "ok"
                  url:
                    type: string
                    example: "/files/sound.mp3"

components:
  schemas:
    Sound:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "sound.mp3"
        url:
          type: string
          example: "/files/sound.mp3"
      required:
        - id
        - name
        - url
